// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-r0fYYzdbf0mRq7evcbk7V_q0kE-Dlfc',
    appId: '1:722070296779:web:dc3455e33b93ee0317234e',
    messagingSenderId: '722070296779',
    projectId: 'brew-crew-62c77',
    authDomain: 'brew-crew-62c77.firebaseapp.com',
    storageBucket: 'brew-crew-62c77.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmnauxicugGvlyWJC7wy6P3Z0l67HmEk4',
    appId: '1:722070296779:android:4658bd956035307417234e',
    messagingSenderId: '722070296779',
    projectId: 'brew-crew-62c77',
    storageBucket: 'brew-crew-62c77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ygy0WDRRLiT6n2slN5S6sVOBp01uzao',
    appId: '1:722070296779:ios:ad5be54bb5b3c63e17234e',
    messagingSenderId: '722070296779',
    projectId: 'brew-crew-62c77',
    storageBucket: 'brew-crew-62c77.appspot.com',
    iosBundleId: 'com.kyle.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ygy0WDRRLiT6n2slN5S6sVOBp01uzao',
    appId: '1:722070296779:ios:ad5be54bb5b3c63e17234e',
    messagingSenderId: '722070296779',
    projectId: 'brew-crew-62c77',
    storageBucket: 'brew-crew-62c77.appspot.com',
    iosBundleId: 'com.kyle.brewCrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-r0fYYzdbf0mRq7evcbk7V_q0kE-Dlfc',
    appId: '1:722070296779:web:30aac03f5e885b5c17234e',
    messagingSenderId: '722070296779',
    projectId: 'brew-crew-62c77',
    authDomain: 'brew-crew-62c77.firebaseapp.com',
    storageBucket: 'brew-crew-62c77.appspot.com',
  );
}
